Since VM runs out of space trying to create both in the same image - scatter image instead
Use sudo instead for apt-get build

diff --git a/.github/workflows/build_and_push_container_to_ghcrio.yml b/.github/workflows/build_and_push_container_to_ghcrio.yml
--- a/.github/workflows/build_and_push_container_to_ghcrio.yml
+++ b/.github/workflows/build_and_push_container_to_ghcrio.yml
@@ -7,7 +7,7 @@ on:
     - 'pre-v*' # Push events to matching pre-v, i.ve pre-v1.0, pre-v20.15.10
 
 jobs:
-  docker:
+  get_parameters:
     runs-on: ubuntu-latest
     steps:
       # Standard checkout step
@@ -22,6 +22,30 @@ jobs:
       - name: get lowercase repo name
         id: get_lowercase_repo_name
         run: echo "::set-output name=repo_name::$(tr '[:upper:]' '[:lower:]' <<< "${{ github.repository }}")"
+      # Set platforms
+      - name: Set platforms
+        id: set_platforms
+        run: echo '::set-output name=platforms::["linux/amd64","linux/arm64"]'
+    outputs:
+      tag_name: ${{ steps.get_tag_name.outputs.tag_name }}
+      repo_name: ${{ steps.get_lowercase_repo_name.outputs.repo_name }}
+      platforms: ${{ steps.set_platforms.outputs.platforms }}
+  docker_scatter_build:
+    needs: get_parameters
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        platform: ${{ fromJSON(needs.get_parameters.outputs.platforms) }}
+      fail-fast: false  # Don't fail if one image fails to run
+    steps:
+      # Standard checkout step
+      - name: Checkout code
+        id: git_checkout
+        uses: actions/checkout@v3
+      # Platform to tag suffix
+      - name: Platform to tag suffix
+        id: platform_to_tag_suffix
+        run: echo "::set-output name=platform_tag::$( echo ${{ matrix.platform }} | tr '/' '-' )"
       # Use qemu to perform multiplatform builds
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1
@@ -47,6 +71,53 @@ jobs:
         with:
           context: .
           file: envm/Dockerfile
-          platforms: linux/amd64,linux/arm64
+          platforms: ${{ matrix.platform }}
           push: true
-          tags: ghcr.io/${{ steps.get_lowercase_repo_name.outputs.repo_name }}:${{ steps.get_tag_name.outputs.tag_name }}
+          tags: ghcr.io/${{ needs.get_parameters.outputs.repo_name }}:${{ needs.get_parameters.outputs.tag_name }}-${{ steps.platform_to_tag_suffix.outputs.platform_tag }}
+
+  tag_manifest:
+    needs: [ get_parameters, docker_scatter_build ]
+    runs-on: ubuntu-latest
+    steps:
+      # Standard checkout step
+      - name: Checkout code
+        id: git_checkout
+        uses: actions/checkout@v3
+      # Log in to GitHub Container registry
+      - name: Login to GitHub Container Registry
+        uses: docker/login-action@v1
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+      # Create manifest file with docker
+      - name: Create and push manifest file
+        id: create_and_push_manifest_file
+        shell: bash
+        run: |
+          # Create and push a manifest file
+          
+          # Install jq
+          echo "Installing jq binary" 1>&2
+          sudo apt-get update -y -qq
+          sudo apt-get install -y -qq \
+            jq
+          
+          # Set manfest name as var
+          echo "Setting manifest name as 'ghcr.io/${{ needs.get_parameters.outputs.repo_name }}:${{ needs.get_parameters.outputs.tag_name }}'" 1>&2
+          manifest_name="ghcr.io/${{ needs.get_parameters.outputs.repo_name }}:${{ needs.get_parameters.outputs.tag_name }}"
+          
+          # Get platform tags from platforms
+          # linux/amd64 to linux-amd64 etc.
+          echo "Reading platform suffixes from get_parameters step" 1>&2
+          readarray -t TAGS_ARRAY < <(jq -rc '.[] | sub("/"; "-")' <<< '${{ needs.get_parameters.outputs.platforms }}')
+          
+          # Create the manifest file
+          echo "Creating the manifest file" 1>&2
+          docker manifest create \
+             "${manifest_name}" \
+             ${TAGS_ARRAY[@]/#/${manifest_name}-}
+          
+          # Push the manifest file
+          echo "Pushing the multi-platform manifest file" 1>&2
+          docker manifest push "${manifest_name}"
